[mypy]
python_version = 3.12
strict = True
files = app, ../environments

[mypy-tests.*]
ignore_errors = True

[mypy-tests.unit.test_conversation_history_repository_creation,tests.unit.test_conversation_history_transactions,tests.unit.test_conversation_history_repository_transitions,tests.unit.test_conversation_history_repository_retention]
ignore_errors = False

[mypy-tests.unit.test_conversation_history_transactions]
disallow_any_explicit = True

[mypy-tests.unit.test_chat_service]
ignore_errors = False
disallow_untyped_defs = False
disallow_incomplete_defs = False
disallow_untyped_calls = False
